package dhcp

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"net"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tianwei/diskless/internal/domain"
	"github.com/tianwei/diskless/internal/storage"
)

type GroupConfig struct {
	Group     domain.Group
	Terminals []domain.Terminal
}

type Renderer struct {
	TFTPRoot    string
	BootFile    string
	EFIBootFile string
	// BootURL 是 iPXE 接管 PXE ROM 后 chainload 的 HTTP 地址（如 "http://192.168.1.5:8080/boot?mac=${net0/mac}"）。
	// 为空时只下发 TFTP 启动文件，不做 HTTP chainload。
	BootURL string
}

func (r Renderer) Render(groups []GroupConfig) (string, error) {
	if r.TFTPRoot == "" || r.BootFile == "" {
		return "", fmt.Errorf("tftp root and boot file are required")
	}

	groups = append([]GroupConfig{}, groups...)
	sort.Slice(groups, func(i, j int) bool { return groups[i].Group.ID < groups[j].Group.ID })

	var b bytes.Buffer
	fmt.Fprintln(&b, "# generated by ndiskless")
	// 只服务有保留地址的机器：各分组网段是真实的 dhcp-range，未登记机器会抢占之后分给客户机的地址；
	// 它们本来也启动不了（/boot 对未知 MAC 返回 404）。`known` 是 dnsmasq 表示“有 dhcp-host 条目”的内置标签。
	fmt.Fprintln(&b, "dhcp-ignore=tag:!known")
	fmt.Fprintln(&b, "enable-tftp")
	fmt.Fprintf(&b, "tftp-root=%s\n", r.TFTPRoot)
	if r.EFIBootFile != "" {
		fmt.Fprintln(&b, "dhcp-match=set:bios,option:client-arch,0")
		fmt.Fprintln(&b, "dhcp-match=set:efi-x86_64,option:client-arch,7")
		fmt.Fprintln(&b, "dhcp-match=set:efi-x86_64,option:client-arch,9")
	}
	if r.BootURL != "" {
		fmt.Fprintln(&b, "dhcp-userclass=set:ipxe,iPXE")
		fmt.Fprintf(&b, "dhcp-boot=tag:ipxe,%s\n", r.BootURL)
		if r.EFIBootFile != "" {
			fmt.Fprintf(&b, "dhcp-boot=tag:!ipxe,tag:bios,%s\n", r.BootFile)
			fmt.Fprintf(&b, "dhcp-boot=tag:!ipxe,tag:!bios,%s\n", r.EFIBootFile)
		} else {
			fmt.Fprintf(&b, "dhcp-boot=tag:!ipxe,%s\n", r.BootFile)
		}
	} else if r.EFIBootFile != "" {
		fmt.Fprintf(&b, "dhcp-boot=tag:bios,%s\n", r.BootFile)
		fmt.Fprintf(&b, "dhcp-boot=tag:!bios,%s\n", r.EFIBootFile)
	} else {
		fmt.Fprintf(&b, "dhcp-boot=%s\n", r.BootFile)
	}

	for _, item := range groups {
		if err := renderGroup(&b, item); err != nil {
			return "", err
		}
	}
	return b.String(), nil
}

func renderGroup(b *bytes.Buffer, item GroupConfig) error {
	g := item.Group
	start, err := netip.ParseAddr(g.StartIP)
	if err != nil || !start.Is4() {
		return fmt.Errorf("invalid group start ip %q", g.StartIP)
	}
	// 没有网关就不下发默认路由。
	if gw := strings.TrimSpace(g.Gateway); gw != "" {
		if _, err := netip.ParseAddr(gw); err != nil {
			return fmt.Errorf("invalid gateway %q", g.Gateway)
		}
	}
	if g.ClientMax <= 0 {
		return fmt.Errorf("client max must be positive")
	}
	end, err := addIPv4(start, g.ClientMax-1)
	if err != nil {
		return err
	}
	tag := tagForGroup(g.ID)
	fmt.Fprintf(b, "\n# group %s\n", g.Name)
	fmt.Fprintf(b, "dhcp-range=set:%s,%s,%s,%s,12h\n", tag, start, end, g.Netmask)
	if gw := strings.TrimSpace(g.Gateway); gw != "" {
		fmt.Fprintf(b, "dhcp-option=tag:%s,option:router,%s\n", tag, gw)
	}
	fmt.Fprintf(b, "dhcp-option=tag:%s,option:netmask,%s\n", tag, g.Netmask)
	if dns := dnsServers(g); dns != "" {
		fmt.Fprintf(b, "dhcp-option=tag:%s,option:dns-server,%s\n", tag, dns)
	}

	terminals := append([]domain.Terminal{}, item.Terminals...)
	sort.Slice(terminals, func(i, j int) bool { return terminals[i].MAC < terminals[j].MAC })
	for _, t := range terminals {
		ip, err := netip.ParseAddr(t.IP)
		if err != nil || !ip.Is4() {
			return fmt.Errorf("invalid terminal ip %q", t.IP)
		}
		mac, err := dnsmasqMAC(t.MAC)
		if err != nil {
			return err
		}
		if lessIPv4(ip, start) || lessIPv4(end, ip) {
			return fmt.Errorf("terminal %s ip %s outside group %s range", t.MAC, t.IP, g.Name)
		}
		fmt.Fprintf(b, "dhcp-host=%s,set:%s,%s\n", mac, tag, t.IP)
	}
	return nil
}

type Runner interface {
	Run(context.Context, string, ...string) ([]byte, error)
}

type ExecRunner struct{}

func (ExecRunner) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	return exec.CommandContext(ctx, name, args...).CombinedOutput()
}

type Manager struct {
	Path     string
	Renderer Renderer
	Runner   Runner
	Logger   *slog.Logger
	// RestartGate 拒绝时只更新配置文件、不动 dnsmasq（备机模式：两台权威 DHCP 会互相 NAK 对方的客户机）。
	// 跳过的重启不会丢：激活时会显式启动 dnsmasq 并读这里写的文件。
	RestartGate func() error
	// BasePath 是 dnsmasq 监听方式的基础配置文件；为空则不接管。
	BasePath string
	// InterfaceFor 返回服务某地址的本机网卡。dhcp_release 发错网卡也返回 0，看起来和成功一样，所以必须选对。
	// 为 nil 时读本机真实网卡。
	InterfaceFor func(netip.Addr) (string, bool)
}

// ReleaseLease 释放某地址上旧 MAC 的租约。租约还在时 dnsmasq 不会把保留地址给新主人
// （日志 "not using configured address X because it is leased to Y"），会改发别的地址。
// 对运行中的 dnsmasq 立即生效，无需重启。
func (m Manager) ReleaseLease(ctx context.Context, ip, mac string) error {
	addr, err := netip.ParseAddr(strings.TrimSpace(ip))
	if err != nil || !addr.Is4() {
		return fmt.Errorf("invalid address %q", ip)
	}
	hw, err := dnsmasqMAC(mac)
	if err != nil {
		return err
	}
	lookup := m.InterfaceFor
	if lookup == nil {
		lookup = localInterfaceFor
	}
	iface, ok := lookup(addr)
	if !ok {
		return fmt.Errorf("no local interface serves %s", addr)
	}
	runner := m.Runner
	if runner == nil {
		runner = ExecRunner{}
	}
	if out, err := runner.Run(ctx, "dhcp_release", iface, addr.String(), hw); err != nil {
		return fmt.Errorf("dhcp_release failed: %w: %s", err, string(out))
	}
	return nil
}

// localInterfaceFor 找到网段包含该地址的本机网卡。
func localInterfaceFor(addr netip.Addr) (string, bool) {
	ifaces, err := net.Interfaces()
	if err != nil {
		return "", false
	}
	for _, iface := range ifaces {
		addrs, err := iface.Addrs()
		if err != nil {
			continue
		}
		for _, a := range addrs {
			prefix, err := netip.ParsePrefix(a.String())
			if err != nil {
				continue
			}
			if prefix.Contains(addr) {
				return iface.Name, true
			}
		}
	}
	return "", false
}

// BaseConfig 描述 dnsmasq 的监听方式。Iface 是面向客户机的网卡；ListenAll 监听所有网卡，
// 以收到交换机从其他 VLAN 中继来的单播请求。只应答已登记机器（dhcp-ignore=tag:!known），放宽监听不会给陌生机器发地址。
type BaseConfig struct {
	Iface     string
	ListenAll bool
}

// RenderBase 生成对应监听方式的基础配置。
func RenderBase(cfg BaseConfig) string {
	var b strings.Builder
	b.WriteString("# generated by ndiskless — how dnsmasq listens; the groups are in ndiskless.conf\n")
	b.WriteString("port=0\n")
	if cfg.ListenAll {
		b.WriteString("except-interface=lo\n")
	} else {
		fmt.Fprintf(&b, "interface=%s\n", cfg.Iface)
	}
	// 与安装程序一致用 bind-interfaces：本机其他配置片段（ubuntu-fan）也用它，不能与 bind-dynamic 混用。
	b.WriteString("bind-interfaces\n")
	b.WriteString("dhcp-authoritative\n")
	return b.String()
}

// SyncBase 写基础配置，有变化时重启 dnsmasq。
func (m Manager) SyncBase(ctx context.Context, cfg BaseConfig) error {
	if m.BasePath == "" {
		return nil
	}
	if !cfg.ListenAll && strings.TrimSpace(cfg.Iface) == "" {
		return fmt.Errorf("client interface is required unless listening on all interfaces")
	}
	return m.writeAndRestart(ctx, m.BasePath, RenderBase(cfg))
}

func (m Manager) Sync(ctx context.Context, groups []GroupConfig) error {
	content, err := m.Renderer.Render(groups)
	if err != nil {
		return err
	}
	return m.writeAndRestart(ctx, m.Path, content)
}

// EnsureRunning 在 dnsmasq 未运行时启动它。HA 下该服务被 disable（防备机抢答），开机不会自启，
// 所以主节点上线时必须调用；RestartGate 保证备机不会启动它。
func (m Manager) EnsureRunning(ctx context.Context) error {
	if m.RestartGate != nil {
		if err := m.RestartGate(); err != nil {
			if m.Logger != nil {
				m.Logger.Info("dnsmasq left stopped", "reason", err.Error())
			}
			return nil
		}
	}
	runner := m.Runner
	if runner == nil {
		runner = ExecRunner{}
	}
	if out, err := runner.Run(ctx, "systemctl", "is-active", "dnsmasq"); err == nil &&
		strings.TrimSpace(string(out)) == "active" {
		return nil // 已在服务；多余的重启会打断进行中的租约
	}
	if out, err := runner.Run(ctx, "systemctl", "reset-failed", "dnsmasq"); err != nil && m.Logger != nil {
		m.Logger.Warn("could not clear dnsmasq's restart counter", "error", err, "output", string(out))
	}
	if out, err := runner.Run(ctx, "systemctl", "start", "dnsmasq"); err != nil {
		return fmt.Errorf("dnsmasq start failed: %w: %s", err, string(out))
	}
	if m.Logger != nil {
		m.Logger.Info("dnsmasq started (active node)")
	}
	return nil
}

// writeAndRestart 先用 dnsmasq 校验内容再写入并重启；文件内容未变时什么都不做。
func (m Manager) writeAndRestart(ctx context.Context, path, content string) error {
	runner := m.Runner
	if runner == nil {
		runner = ExecRunner{}
	}
	// 内容相同就不重启：每次分组/客户机变更和启动都会同步，无谓重启会打断正在 PXE 的机器。
	previous, prevErr := os.ReadFile(path)
	if prevErr == nil && string(previous) == content {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".ndiskless-dnsmasq-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if out, err := runner.Run(ctx, "dnsmasq", "--test", "--conf-file="+tmpName); err != nil {
		return fmt.Errorf("dnsmasq config test failed: %w: %s", err, string(out))
	}
	if err := os.Rename(tmpName, path); err != nil {
		return err
	}
	if m.RestartGate != nil {
		if gateErr := m.RestartGate(); gateErr != nil {
			if m.Logger != nil {
				m.Logger.Info("dnsmasq config written; restart withheld", "reason", gateErr.Error())
			}
			return nil
		}
	}
	// systemd 默认 10 秒内最多启动 5 次，连续变更很快超限，之后服务拒绝启动、DHCP 彻底停掉。
	// 重启前先清计数；尽力而为，失败不影响重启。
	if out, err := runner.Run(ctx, "systemctl", "reset-failed", "dnsmasq"); err != nil && m.Logger != nil {
		m.Logger.Warn("could not clear dnsmasq's restart counter", "error", err, "output", string(out))
	}
	// 必须 restart 不能 reload：reload 即 SIGHUP，dnsmasq 收到后不重读主配置文件，新配置不会生效。
	if out, err := runner.Run(ctx, "systemctl", "restart", "dnsmasq"); err != nil {
		// 退回旧文件，下次同步才会看到内容不同并重试；否则「内容没变」会一直跳过重启。
		var rollbackErr error
		if prevErr == nil {
			rollbackErr = os.WriteFile(path, previous, 0o644)
		} else {
			rollbackErr = os.Remove(path)
		}
		if rollbackErr != nil && m.Logger != nil {
			m.Logger.Warn("could not roll back dnsmasq config after a failed restart", "path", path, "error", rollbackErr)
		}
		// restart 失败时 dnsmasq 已经停了，按旧配置再拉起来，否则 DHCP 要停到下次变更。
		if rollbackErr == nil {
			if out2, err2 := runner.Run(ctx, "systemctl", "restart", "dnsmasq"); err2 != nil && m.Logger != nil {
				m.Logger.Warn("dnsmasq did not come back on the previous config", "error", err2, "output", string(out2))
			}
		}
		return fmt.Errorf("dnsmasq restart failed: %w: %s", err, string(out))
	}
	return nil
}

func addIPv4(ip netip.Addr, offset int) (netip.Addr, error) {
	v := ip.As4()
	n := uint32(v[0])<<24 | uint32(v[1])<<16 | uint32(v[2])<<8 | uint32(v[3])
	n += uint32(offset)
	return netip.AddrFrom4([4]byte{byte(n >> 24), byte(n >> 16), byte(n >> 8), byte(n)}), nil
}

func lessIPv4(a, b netip.Addr) bool {
	aa, bb := a.As4(), b.As4()
	for i := range aa {
		if aa[i] != bb[i] {
			return aa[i] < bb[i]
		}
	}
	return false
}

func tagForGroup(id string) string {
	id = strings.ToLower(id)
	var b strings.Builder
	for _, r := range id {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	if b.Len() == 0 {
		return "group"
	}
	return b.String()
}

func dnsmasqMAC(mac string) (string, error) {
	mac = storage.NormalizeMAC(mac)
	if len(mac) != 12 {
		return "", fmt.Errorf("invalid terminal mac %q", mac)
	}
	parts := make([]string, 0, 6)
	for i := 0; i < len(mac); i += 2 {
		parts = append(parts, mac[i:i+2])
	}
	return strings.Join(parts, ":"), nil
}

func dnsServers(g domain.Group) string {
	var out []string
	if g.DNS1 != "" {
		out = append(out, g.DNS1)
	}
	if g.DNS2 != "" {
		out = append(out, g.DNS2)
	}
	return strings.Join(out, ",")
}
